"""empty message

Revision ID: 480776d4cd74
Revises: b85a80d3be34
Create Date: 2022-11-02 11:39:29.157917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480776d4cd74'
down_revision = 'b85a80d3be34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breakfast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('prep_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breakfast')
    # ### end Alembic commands ###
